exo11:
	gcc exo11.c -o exo11
	./exo11
	rm exo11

exo12:
	gcc exo12.c -o exo12
	./exo12
	rm exo12

exo13:
	gcc exo13.c -o exo13
	./exo13
	rm exo13

exo14:
	gcc exo14.c -o exo14
	./exo14
	rm exo14

exo15:
	gcc exo15.c -o exo15
	./exo15
	rm exo15

exo16:
	gcc exo16.c -o exo16
	./exo16
	rm exo16

exo17:
	gcc exo17.c -o exo17
	./exo17
	rm exo17

exo18:
	gcc exo18.c -o exo18
	./exo18
	rm exo18

exo19:
	gcc exo19.c -o exo19
	./exo19
	rm exo19

exo20:
	gcc exo20.c -o exo20
	./exo20
	rm exo20

exo21:
	gcc exo21.c -o exo21
	./exo21
	rm exo21

exo22:
	gcc exo22.c -o exo22
	./exo22
	rm exo22

exo23:
	gcc exo23.c -o exo23
	./exo23
	rm exo23
