test: exo18 clean

exo18: exo18.c
	gcc -o programme exo18.c
	./programme azerty qwerty
	./programme bonjour salut
	./programme Raphael thomas
	./programme paris montreal
	./programme 181818 27272
	./programme 1 7272
	
clean:
	rm -f programme
